.github/workflows/bump-version-and-tag.yaml, .github/workflows/publish-configuration.yaml
=> try to fix the workflows

configs/oasis-borrow/index.ts
=> testing change

.github/workflows/publish-configuration.yaml, configs/test-config/index.ts
=> Test secret value

.github/workflows/publish-configuration.yaml
=> disable artifact upload

configs/oasis-borrow/index.ts
=> sync toggles

.eslintrc.json, configs/oasis-borrow/index.ts
=> update eslint config

.eslintrc.json
=> update correct rule

.github/workflows/publish-configuration.yaml
=> added manual trigger

configs/oasis-borrow/index.ts
=> sync with ob

configs/oasis-borrow/index.ts
=> Disable DSR for testing

configs/oasis-borrow/index.ts
=> fixes build

configs/oasis-borrow/index.ts
- changed `UseNetworkSwitcherForks` to show how all of this is working
=> This commit will enable network switcher forks for oasis-borrow

configs/oasis-borrow/index.ts
Reverts https://github.com/OasisDEX/oazo-configuration/pull/30
=> Revert test changes

configs/oasis-borrow/index.ts
- added `parameters` with top banner configured
=> Added parameters alongside features

configs/oasis-borrow/index.ts
Added exclamation mark to test the changes being made.
=> Test update top banner

configs/oasis-borrow/index.ts
- Enabled `SparkProtocolStopLoss` on staging
=> Added SparkProtocolStopLoss

configs/oasis-borrow/index.ts
- Created `NewNavigation` feature flag for the purpose of https://app.shortcut.com/oazo-apps/epic/12024.
=> Create NewNavigation feature flag

configs/oasis-borrow/getRpcConfig.ts, configs/oasis-borrow/index.ts
Story details: https://app.shortcut.com/oazo-apps/story/12093
=> feat: [sc-12093] [backend] - add call config to oazo-configuration

configs/oasis-borrow/getNavigation.ts
- changed place where `extra` property is in navigation config as it's common per protocol
=> Navigation extra property location change

configs/oasis-borrow/getNavigation.ts
=> Fix navigation config typo

configs/oasis-borrow/getRpcConfig.ts, configs/oasis-borrow/index.ts
- add stage and source to rpcConfig
=> feat: add stage and source to rpcConfig

configs/oasis-borrow/getNavigation.ts
=> Update navigation tokens

configs/oasis-borrow/getParameters.ts
Following issues with closing to stable coins im adding these params.
=> 'closeDisabledFor' collateral/strategytypes in aave like

configs/oasis-borrow/getParameters.ts
Added the mirrored config"adjustDisabledFor" (same as closeDisabledFor)
=> Added the mirrored config"adjustDisabledFor" (same as closeDisabledFor)

configs/oasis-borrow/getFeatures.ts
- Set `NewNavigation` feature flag to `true` by default.
=> set NewNavigation to true

configs/oasis-borrow/getFeatures.ts
* Set SparkStopLoss feature flag to true by default.
=> set SparkProtocolStopLoss to true

configs/oasis-borrow/getFeatures.ts
New feature: BaseNetworkEnabled
=> New feature: BaseNetworkEnabled

configs/oasis-borrow/getFeatures.ts
- Created `MorphoBlue` feature flag for the purpose of https://app.shortcut.com/oazo-apps/epic/12178.
=> Create MorphoBlue feature flag

configs/oasis-borrow/getNavigation.ts
- Added dummy text for Morpho Blue navigation panel.
=> Add Morpho Blue navigation settings

.github/workflows/lint-configs.yaml
- Add build step to lint workflow
=> Add build step to lint workflow

configs/oasis-borrow/getParameters.ts
Add banner for UK based users.
=> add location based baner.

configs/oasis-borrow/getParameters.ts
Change AaveV3@Base flashloan token to WETH (higher liquidity)
=> Change AaveV3@Base flashloan token

configs/oasis-borrow/getFeatures.ts
=> NewPortfolio Feature Flag

configs/oasis-borrow/getFeatures.ts
- added morpho blue feature toggles
- removed ajna reusable dpm as it will be turned on as default on reluanch
=> Morpho blue feature toggles

configs/oasis-borrow/getFeatures.ts
- added maker tenderly FT to be used on maker positions while forking mainnet using tenderly (history won't be available)
=> Maker tenderly feature toggle

configs/oasis-borrow/getFeatures.ts
- turn `useRpcGateway` ff to `true`
=> feat: enable rpc gateway

shared/denomination-symbol.ts
- Add USDT to denomination enum
=> feat(denomination symbols): add USDT denomination symbol

configs/oasis-borrow/getFeatures.ts
=> Enable NewPortfolio

configs/oasis-borrow/getFeatures.ts
=> Enable SparkWBTCDAI

configs/oasis-borrow/getParameters.ts
=> feat: change staging subgraph base url

configs/oasis-borrow/getParameters.ts
Reverts OasisDEX/oazo-configuration#72
=> Revert "feat: change staging subgraph base url"

configs/oasis-borrow/getFeatures.ts
- Added `AjnaBase` feature flag.
=> Add `AjnaBase` feature flag

configs/oasis-borrow/getFeatures.ts
=> Enable Aave/Spark history on staging

configs/oasis-borrow/getFeatures.ts
sorry mr Ciarka, git confused me.
=> Enable History

configs/oasis-borrow/getFeatures.ts
Added OmniPnlModal feature toggle.
=> OmniPnlModal

configs/oasis-borrow/getFeatures.ts
=> AaveLikeSimpleEarn toggles

configs/oasis-borrow/getFeatures.ts
- Turned of Ajna Base on staging for testing purposes
=> Turn of Ajna Base on staging

configs/oasis-borrow/getFeatures.ts
- Turned off Ajna Base feature toggle
=> Turn off Ajna Base

configs/oasis-borrow/getFeatures.ts
- Turned on Ajna Base for staging
=> Turn on Ajna Base for staging

configs/oasis-borrow/getNavigation.ts
=> Update Morpho Blue promo link in navigation

configs/oasis-borrow/getFeatures.ts
- Set `MorphoBlue` feature flag to `true`.
=> Turn on MorphoBlue feature flag

configs/oasis-borrow/getParameters.ts
Configuration for the minimum value of the position to setup automation.
=> [SC-14247] Configuration for the minimum value of the position

configs/oasis-borrow/getFeatures.ts
=> SparkProtectionLambdaEthereum

configs/oasis-borrow/getFeatures.ts
=> Add omni like ft for aave

configs/oasis-borrow/getParameters.ts
updated the base subgraph URL to one with default routes
=> chore: update base sugraph url

configs/oasis-borrow/getFeatures.ts
SparkTrailingStopLossLambdaEthereum
=> SparkTrailingStopLossLambdaEthereum

configs/oasis-borrow/getFeatures.ts
AaveV3LambdaSuppressValidation
Disables errors blocking the CTA button.
=> AaveV3LambdaSuppressValidation

configs/oasis-borrow/getFeatures.ts
Added enable refinance flag for refinance feature
=> Added enable refinance flag

configs/oasis-borrow/getFeatures.ts
- Added `Erc4626Vaults`, `Erc4626VaultsSafetySwitch` and `Erc4626VaultsSuppressValidation` feature flags.
=> Add ERC-4626 related feature flags

configs/oasis-borrow/getFeatures.ts
=> OmniKitDebug

configs/oasis-borrow/getFeatures.ts
- added safety switch flag
- added suppress validation flag
=> Add refinance flags

configs/oasis-borrow/getFeatures.ts
- Added `ProductHubDebug` feature flag
=> Add `ProductHubDebug` feature flag

configs/oasis-borrow/getFeatures.ts
=> Add LambdaAutomations

configs/oasis-borrow/index.ts
Refactor config helper function to use params object
=> Refactor config helper function to use params object

configs/oasis-borrow/getFeatures.ts
=> Disable Net Value Check

configs/oasis-borrow/getFeatures.ts
=> Enabled refinance

configs/oasis-borrow/getFeatures.ts
Disable Refinance as a P1 measure
=> Disable Refinance

configs/oasis-borrow/getFeatures.ts
- added Rays ft in borrow config
=> Add Rays FT to borrow

configs/oasis-borrow/getFeatures.ts
This pull request enables the Refinance feature in the oasis-borrow configuration on prod.
=> Enable Refinance in oasis-borrow configuration

configs/oasis-borrow/getParameters.ts
- added isolated collateral tokens aave
=> Add isolated collateral tokens aave

configs/oasis-borrow/getParameters.ts
Added Oasis Borrow announcement parameter
=> Added Oasis Borrow announcement parameter

configs/oasis-borrow/getParameters.ts
=> enable announcement

configs/oasis-borrow/getFeatures.ts
=> RaysDailyChallenge

configs/oasis-borrow/getParameters.ts
=> Remove announcement

configs/oasis-borrow/getParameters.ts
2x $RAYS for Multiply and Yield Loop Trades Announcement
=> 2x $RAYS for Multiply and Yield Loop Trades

configs/oasis-borrow/getFeatures.ts
=> Add Newsletter FT

configs/oasis-borrow/getFeatures.ts
=> Enable newsletter on staging

configs/oasis-borrow/getFeatures.ts
=> Enable daily rays

configs/oasis-borrow/getParameters.ts
=> Spark x2 banner

configs/oasis-borrow/getParameters.ts
=> Add sky announcement

configs/oasis-borrow/getParameters.ts
=> Fix announcement

configs/oasis-borrow/getParameters.ts
=> revert icon change

configs/oasis-borrow/getFeatures.ts
=> Added SkyUpgrade toggle

configs/oasis-borrow/getFeatures.ts
=> Enable newsletter globally

configs/oasis-borrow/getNavigation.ts, configs/oasis-borrow/getParameters.ts
This pull request includes changes to improve the readability and maintainability of the configuration files in the `configs/oasis-borrow` directory. The changes mainly focus on formatting and conditional logic adjustments.
Formatting improvements:
* [`configs/oasis-borrow/getNavigation.ts`](diffhunk://#diff-b4e6b8ff987f51595abfc82f778caeb3d9ef10eae57a5e9a950585237c2dc3e9L7-R115): Reformatted the descriptions and titles to use a consistent multiline string format.
Conditional logic adjustments:
* [`configs/oasis-borrow/getParameters.ts`](diffhunk://#diff-ecbf6cbadf37a716205e686d021c8ef8de118aea0f8ff0b66a20cc525ad15dadL14-R22): Added a conditional block to handle different announcements based on the environment (`notProduction`).
=> Morpho banner

configs/earn-protocol/getFleetConfig.ts
Improve the structure of the fleet configuration and introduce an empty configuration to enhance type safety.
=> Refactor fleet configuration for type safety

package.json, shared/token-symbol.ts, shared/tokens.ts
=> feat: add missing tokens (CBBTC / WEETH)

configs/earn-protocol/getFleetConfig.ts
=> Add mainnet fleets earn app

configs/oasis-borrow/getParameters.ts
Revise the messaging and URL for the $SUMR token claim announcement to provide clearer information and direct users to the correct site.
=> Update claim announcement for $SUMR token

configs/earn-protocol/index.ts
=> Disable maintenance

configs/oasis-borrow/getParameters.ts
=> Announce new summer.fi

configs/earn-protocol/getFeatures.ts, configs/earn-protocol/index.ts
-Added migration feature to earn protocol
=> Add migration feature to earn protocol

configs/earn-protocol/getFleetConfig.ts
Introduce a bonus configuration to the fleet settings, allowing for customizable multipliers and descriptions. Refactor the vault handling to streamline address processing.
=> Add bonus configuration to fleet settings and refactor vault handling

configs/earn-protocol/getFleetConfig.ts
=> Enable sonic vault

configs/earn-protocol/getFleetConfig.ts
Reverts OasisDEX/oazo-configuration#175
=> Revert "Enable sonic vault"

configs/earn-protocol/getFleetConfig.ts
Reverts OasisDEX/oazo-configuration#176 (Enables sonic vault)
=> Revert "Revert "Enable sonic vault""
